-- AIanime: real weekly release schedule.
-- Safe to run repeatedly in Supabase SQL Editor.

create table if not exists public.anime_schedule (
  id bigint generated by default as identity primary key,
  schedule_uid text not null unique,
  anime_slug text not null,
  mal_id bigint,
  title text not null,
  title_ru text,
  poster_url text,
  episode_number integer,
  broadcast_day text,
  broadcast_time text,
  broadcast_timezone text default 'Asia/Tokyo',
  airing_at timestamptz not null,
  source text not null default 'jikan',
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists anime_schedule_airing_at_idx on public.anime_schedule(airing_at);
create index if not exists anime_schedule_anime_slug_idx on public.anime_schedule(anime_slug);
create index if not exists anime_schedule_mal_id_idx on public.anime_schedule(mal_id);
create index if not exists anime_schedule_source_idx on public.anime_schedule(source);

comment on table public.anime_schedule is 'Real release/broadcast schedule for AIanime. Filled by /api/cron/schedule from Jikan/MAL schedules.';
comment on column public.anime_schedule.airing_at is 'Exact broadcast datetime normalized to UTC. UI formats it in AIANIME_SCHEDULE_TIME_ZONE.';
comment on column public.anime_schedule.schedule_uid is 'Stable unique key for weekly upsert: source + anime + date + broadcast time.';
