-- AIanime: real weekly release schedule.
-- Safe to run repeatedly in Supabase SQL Editor.
-- This migration also repairs an older/incomplete anime_schedule table if it already exists.

create table if not exists public.anime_schedule (
  id bigint generated by default as identity primary key,
  schedule_uid text,
  anime_slug text,
  mal_id bigint,
  title text,
  title_ru text,
  poster_url text,
  episode_number integer,
  broadcast_day text,
  broadcast_time text,
  broadcast_timezone text default 'Asia/Tokyo',
  airing_at timestamptz,
  source text default 'jikan',
  raw jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- If the table already existed from an older build, create table if not exists
-- does not add new columns. Add every column explicitly before indexes/comments.
alter table public.anime_schedule add column if not exists id bigint generated by default as identity;
alter table public.anime_schedule add column if not exists schedule_uid text;
alter table public.anime_schedule add column if not exists anime_slug text;
alter table public.anime_schedule add column if not exists mal_id bigint;
alter table public.anime_schedule add column if not exists title text;
alter table public.anime_schedule add column if not exists title_ru text;
alter table public.anime_schedule add column if not exists poster_url text;
alter table public.anime_schedule add column if not exists episode_number integer;
alter table public.anime_schedule add column if not exists broadcast_day text;
alter table public.anime_schedule add column if not exists broadcast_time text;
alter table public.anime_schedule add column if not exists broadcast_timezone text default 'Asia/Tokyo';
alter table public.anime_schedule add column if not exists airing_at timestamptz;
alter table public.anime_schedule add column if not exists source text default 'jikan';
alter table public.anime_schedule add column if not exists raw jsonb default '{}'::jsonb;
alter table public.anime_schedule add column if not exists created_at timestamptz default now();
alter table public.anime_schedule add column if not exists updated_at timestamptz default now();

-- Fill safe defaults only for technical columns so old rows do not break indexes.
-- Old rows without airing_at are ignored by the real schedule UI and can be overwritten by cron.
update public.anime_schedule
set
  schedule_uid = coalesce(schedule_uid, 'legacy:' || coalesce(id::text, md5(random()::text || clock_timestamp()::text))),
  broadcast_timezone = coalesce(nullif(broadcast_timezone, ''), 'Asia/Tokyo'),
  source = coalesce(nullif(source, ''), 'jikan'),
  raw = coalesce(raw, '{}'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now())
where schedule_uid is null
   or broadcast_timezone is null
   or source is null
   or raw is null
   or created_at is null
   or updated_at is null;

-- Protect unique upsert key from possible old duplicate rows.
with ranked as (
  select
    ctid,
    schedule_uid,
    row_number() over (partition by schedule_uid order by ctid) as rn
  from public.anime_schedule
  where schedule_uid is not null
)
update public.anime_schedule s
set schedule_uid = s.schedule_uid || ':dup:' || md5(random()::text || clock_timestamp()::text)
from ranked r
where s.ctid = r.ctid and r.rn > 1;

create unique index if not exists anime_schedule_schedule_uid_idx on public.anime_schedule(schedule_uid);
create index if not exists anime_schedule_airing_at_idx on public.anime_schedule(airing_at);
create index if not exists anime_schedule_anime_slug_idx on public.anime_schedule(anime_slug);
create index if not exists anime_schedule_mal_id_idx on public.anime_schedule(mal_id);
create index if not exists anime_schedule_source_idx on public.anime_schedule(source);

comment on table public.anime_schedule is 'Real release/broadcast schedule for AIanime. Filled by /api/cron/schedule from Jikan/MAL schedules.';
comment on column public.anime_schedule.airing_at is 'Exact broadcast datetime normalized to UTC. UI formats it in AIANIME_SCHEDULE_TIME_ZONE.';
comment on column public.anime_schedule.schedule_uid is 'Stable unique key for weekly upsert: source + anime + date + broadcast time.';
